AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create pipeline-dashboard application.
Parameters:
  PipelinePattern:
    Type: String
Resources:
  PipelineDashboardEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create CloudWatch metrics from CodePipeline events
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/PipelineDashboardEventHandler
      Events:
        PipelineEventRule:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Pipeline Execution State Change
                - CodePipeline Stage Execution State Change
                - CodePipeline Action Execution State Change
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CodePipelineReadOnlyPolicy:
            PipelineName: !Ref PipelinePattern
  PipelineDashboardGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Description: Build CloudWatch dashboard from CloudWatch metrics
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/PipelineDashboardGenerator
      Timeout: 60
      Events:
        DashboardEventRule:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
      Policies:
        - CloudWatchDashboardPolicy: {}